name: Execução da aplicação e testes

on: 
  workflow_dispatch

jobs:  
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout no repositório
        uses: actions/checkout@v4

      - name: Instalando as dependências
        run: npm run install:all

      - name: Executando API
        run: npm run dev:backend &

      - name: Executando WEB
        run: npm run dev:frontend & 

      - name: Executando testes de API
        run: npm run  test
        

      
    
    
    
