name: Execução da aplicação e testes

on: 
  workflow_dispatch

jobs:  
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout no repositório
        uses: actions/checkout@v4

      - name: Instalando as dependências
        run: npm run install:all

      - name: Executando API
        run: npm run dev:backend &

      - name: Executando WEB
        run: npm run dev:frontend & 
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Instala dependências
        run: npm install
        
      - name: Executando testes de API
        run: npm run test

      - name: Executando testes E2E
        run: npm run test:e2e
        

      
    
    
    
